platform: linux

image_resource:
  type: docker-image
  source:
#    repository: maven
    repository: ubuntu
    tag: latest

inputs:
  - name: git-repo
  - name: artifacts
  
outputs:
- name: workarea
  
run:
  path: ./git-repo/concourse/shared/tasks/build-image.sh