platform: linux

image_resource:
  type: docker-image
  source:
#    repository: maven
    repository: gradle
    tag: latest

inputs:
  - name: git-repo
  - name: version
  
outputs:
- name: artifacts
  
run:
  path: ./git-repo/concourse/shared/tasks/build-package.sh  
params: 
  version: version/number
  LOCAL_REPO:
  REPO_KEY:
  REPO_SECRET:
