platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: latest

params:
  LOCAL_REPO:
  REPO_KEY:
  REPO_SECRET:

inputs:
  - name: git-repo

outputs:
  - name: git-repo

    
run:
  path: ./git-repo/concourse/shared/tasks/code-quality.sh