platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
  - name: git-dev
outputs:
  - name: comments
    
run:
  path: ./git-dev/concourse/shared/tasks/tracker.sh  
