platform: linux

image_resource:
  type: docker-image
  source:
#    repository: maven
    repository: gradle
    tag: latest

params:
  LOCAL_REPO: ((LOCAL_REPO))
  REPO_KEY: ((REPO_KEY))
  REPO_SECRET: ((REPO_SECRET))

inputs:
  - name: git-repo
outputs:
  - name: git-repo
    
run:
  path: ./git-repo/concourse/shared/tasks/unit-test.sh  
