platform: linux

image_resource:
  type: docker-image
  source:
#    repository: maven
    repository: gradle
    tag: latest

inputs:
  - name: git-repo
outputs:
  - name: git-repo
    
run:
  path: ./git-repo/concourse/shared/tasks/unit-test.sh  
