apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: humourmind/spring-music
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kubectl:
    manifests:
    - k8s/*
