spring:
  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
<<<<<<< HEAD
  endpoint:
    health:
      show-details: always

=======
<<<<<<< HEAD
<<<<<<< HEAD
  endpoint:
    health:
      show-details: always
=======
<<<<<<< HEAD
>>>>>>> Support Boot 2.0
=======
>>>>>>> local change

#server:
#  port: 8070
>>>>>>> initial tekton commit
---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost/music"
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

---
spring:
  profiles: postgres
  datasource:
    url: "jdbc:postgresql://localhost/music"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
<<<<<<< HEAD
=======
---
spring:
  profiles: mongodb
  data:
    mongodb:
      database: albumDB
#      uri: ${vcap.services.mongo-cups.credentials.endpoint}
>>>>>>> initial tekton commit
