---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-music
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 50  
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      #serviceAccountName: spring-sa
      containers:
      - name: spring-music
        #image: harbor.pcf.humourmind.com/spring/spring-music:blue
        image: humourmind/spring-music:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "768Mi"
            cpu: "300m"
          limits:
            memory: "768Mi"
            cpu: "750m"
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/env
            port: web
          initialDelaySeconds: 55
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/env
            port: web
          initialDelaySeconds: 60
          periodSeconds: 1 
          failureThreshold: 1
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: "app"
      #               operator: In
      #               values:
      #               - spring-music
      #         topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-music
  labels:
    app: spring-music
spec:
  selector:
    app: spring-music
  ports:
  - name: web
    port: 80
    targetPort: 8080
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: spring-music
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    ingress.kubernetes.io/rewrite-target: /
#    ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  rules:
#  - host: spring-music.pksapps.humourmind.com
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: spring-music
#          servicePort: 80
#      - path: /*
#        backend:
#          serviceName: spring-music
#          servicePort: 80
