groups:
- name: dev
  jobs:
  - unit-test
  - code-coverage
  - code-quality
  - unit-pkg
  - dev-deploy
  - dev-tas4k8s-deploy
- name: stage
  jobs:
  - vat
  - sast
  - dast
  - iast
  - stage-deploy
  - stage-tas4k8s-deploy
  - reg-test
  - int-test
  - load-test
- name: pre-prod
  jobs:
  - approval
  - pre-prod-deploy
  - pre-prod-tas4k8s-deploy

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: latest

resources:

- name: git-repo
  type: git
  source:
    uri: https://github.com/srinivasa-vasu/s-music.git
    branch: master
    
- name: version
  type: semver
  source:
    initial_version: 1.0.0
    driver: gcs
    bucket: cn-pcf-bkt
    json_key: {{gcp_service_account_key}}
    key: current-version

- name: artifacts
  type: gcs-resource
  source:
    bucket: cn-pcf-bkt
    json_key: {{gcp_service_account_key}}
    regexp: releases/spring-music-(.*).jar

- name: tas-dev
  type: cf
  source:
    api: {{cf-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space-dev}}

- name: tas4k8s-dev
  type: cf
  source:
    api: {{cf-4-k8s-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space-dev}}    
    
- name: tas-stage
  type: cf
  source:
    api: {{cf-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space-stage}}

- name: tas4k8s-stage
  type: cf
  source:
    api: {{cf-4-k8s-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space-stage}}    

- name: tas-pre-prod
  type: cf
  source:
    api: {{cf-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space-preprod}}

- name: tas4k8s-pre-prod
  type: cf
  source:
    api: {{cf-4-k8s-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space-preprod}}    


jobs:

- name: unit-test
  serial: true
  plan:
  - get: git-repo
    trigger: true
  - task: unit-test
    file: git-repo/concourse/shared/tasks/unit-test.yml

- name: code-coverage
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - unit-test
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: code-quality
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - code-coverage
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: unit-pkg
  serial_groups: [version]
  plan:
  - get: git-repo
    trigger: true
    passed:
    - code-quality
    - unit-test
  - get: version
    params: {bump: final}
  - task: build-package
    file: git-repo/concourse/shared/tasks/build-package.yml
  - put: artifacts
    params: 
      file: artifacts/spring-music-*.jar
  - put: version
    params: {bump: minor}

- name: dev-deploy
  serial: true
  plan:
  - get: artifacts
    trigger: true
    passed:
    - unit-pkg
  - get: git-repo
    passed:
    - unit-pkg
  - put: tas-dev
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar

- name: dev-tas4k8s-deploy
  serial: true
  plan:
  - get: artifacts
    trigger: true
    passed:
    - unit-pkg
  - get: git-repo
    passed:
    - unit-pkg
  - put: tas4k8s-dev
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar      

- name: vat
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - dev-deploy
    - dev-tas4k8s-deploy
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: sast
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - dev-deploy
    - dev-tas4k8s-deploy
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: dast
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - dev-deploy
    - dev-tas4k8s-deploy
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: iast
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - dev-deploy
    - dev-tas4k8s-deploy
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: stage-deploy
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
      - iast
      - sast
      - dast
  - get: artifacts
    trigger: true
    passed:
    - unit-pkg
    - dev-deploy
  - put: tas-stage
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar
      current_app_name: spring-music

- name: stage-tas4k8s-deploy
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
      - iast
      - sast
      - dast
  - get: artifacts
    trigger: true
    passed:
    - unit-pkg
    - dev-tas4k8s-deploy
  - put: tas4k8s-stage
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar
      current_app_name: spring-music            

- name: int-test
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - stage-deploy
    - stage-tas4k8s-deploy
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: reg-test
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - stage-deploy    
    - stage-tas4k8s-deploy
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: load-test
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - reg-test
    - int-test
  - task: ext-test
    file: git-repo/concourse/shared/tasks/ext-test.yml

- name: approval
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - load-test    

- name: pre-prod-deploy
  serial: true
  plan:
  - get: git-repo
    passed:
      - approval
  - get: artifacts
    trigger: true
    passed:
    - unit-pkg
    - stage-deploy
  - put: tas-pre-prod
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar
      current_app_name: spring-music  

- name: pre-prod-tas4k8s-deploy
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
      - approval
  - get: artifacts
    trigger: true
    passed:
    - unit-pkg
    - stage-tas4k8s-deploy
  - put: tas4k8s-pre-prod
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar
      current_app_name: spring-music      