groups:
- name: dev
  jobs:
  - unit-test
  - unit-pkg
  - dev-deploy
- name: stage
  jobs:
  - code-coverage
  - code-quality
  - iast
  - stage-deploy
- name: pre-prod
  jobs:
  - int-test
  - load-test
  - pre-prod-deploy

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: latest

resources:

- name: git-repo
  type: git
  source:
    uri: https://github.com/srinivasa-vasu/s-music.git
    branch: master
    
- name: version
  type: semver
  source:
    initial_version: 1.0.0
    driver: gcs
    bucket: cn-pcf-bkt
    json_key: {{gcp_service_account_key}}
    key: current-version

- name: artifacts
  type: gcs-resource
  source:
    bucket: cn-pcf-bkt
    json_key: {{gcp_service_account_key}}
    regexp: releases/spring-music-(.*).jar

- name: cf-dev
  type: cf
  source:
    api: {{cf-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space-dev}}
    
- name: cf-stage
  type: cf
  source:
    api: {{cf-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-space-stage}}

- name: cf-pre-prod
  type: cf
  source:
    api: {{cf-api}}
    skip_cert_check: true
    organization: {{cf-organization}}
    username: {{cf-username}}
    password: {{cf-password}}
    space: {{cf-pre-prod-stage}}


jobs:

- name: unit-test
  serial: true
  plan:
  - get: git-repo
    trigger: true
  - task: unit-test
    file: git-repo/concourse/shared/tasks/unit-test.yml

- name: unit-pkg
  serial_groups: [version]
  plan:
  - get: git-repo
    trigger: true
    passed:
    - unit-test
  - get: version
    params: {bump: final}
  - task: build-package
    file: git-repo/concourse/shared/tasks/build-package.yml
  - put: artifacts
    params: 
      file: artifacts/spring-music-*.jar
  - put: version
    params: {bump: minor}

- name: dev-deploy
  plan:
  - get: artifacts
    trigger: true
    passed:
    - unit-pkg
  - get: git-repo
    passed:
    - unit-pkg
  - put: cf-dev
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar

- name: code-coverage
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - dev-deploy

- name: code-quality
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - code-coverage

- name: iast
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - code-quality

- name: stage-deploy
  plan:
  - get: git-repo
    passed:
      - iast
  - get: artifacts
    passed:
      - dev-deploy
  - put: cf-stage
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar
      current_app_name: spring-music

- name: int-test
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - stage-deploy

- name: load-test
  serial: true
  plan:
  - get: git-repo
    trigger: true
    passed:
    - int-test

- name: pre-prod-deploy
  plan:
  - get: git-repo
    passed:
      - load-test
  - get: artifacts
    passed:
      - dev-deploy
      - stage-deploy
  - put: cf-pre-prod
    params:
      manifest: git-repo/manifest.yml
      path: artifacts/spring-music-*.jar
      current_app_name: spring-music      